#:schema node_modules/wrangler/config-schema.json
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "nanoocdn"
workers_dev = true
compatibility_date = "2024-09-25"
main = "src/index.js"
upload_source_maps = true
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"

[vars]
B2_APPLICATION_KEY_ID = "0038f4a4d378b380000000013"
B2_ENDPOINT = "s3.eu-central-003.backblazeb2.com"
BUCKET_NAME = "nanoo-assets"
ALLOW_LIST_BUCKET = "false"
RCLONE_DOWNLOAD = "false"
CDN_VERSION = "2.2.5"

[observability]
enabled = true

# Smart Placement
# https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# Routes & Domain
[[routes]]
pattern = "cdn.nanoolabs.dev"
custom_domain = true
